;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="AtkPhys.Slash",DevComment="")
+GameplayTagList=(Tag="AtkPhys.Thrust",DevComment="")
+GameplayTagList=(Tag="DmgLevel.Large",DevComment="")
+GameplayTagList=(Tag="DmgLevel.Middle",DevComment="")
+GameplayTagList=(Tag="DmgLevel.Small",DevComment="")

